10 create reaction table and model
Code-the-Dream-School/herring-team4 pull request #14
Opened 2024-11-27 01:10 UTC by JacinthaDev

#10

2024-11-27 04:44 UTC, Mariela-t approved these changes

2024-12-04 19:20 UTC, christopher-ga reviewed
LGTM

2024-12-04 19:25 UTC, christopher-ga approved these changes

2024-12-05 23:57 UTC, christopher-ga requested changes
Merge conflicts should be resolved before merge.

2024-12-06 22:42 UTC, JacinthaDev commented
Conflicts resovled

2024-12-06 22:42 UTC, merged